// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchPreview(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['FetchPreview'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetNumberOfFiles(arg1) {
  return window['go']['main']['App']['GetNumberOfFiles'](arg1);
}

export function ProcessImages(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ProcessImages'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
