// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchPreview(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<main.returnStruct>;

export function GetNumberOfFiles(arg1:string):Promise<number>;

export function ProcessImages(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<main.returnStruct>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;
